services:
  db:
    image: mysql:8.0
    env_file:
      - ../.env
    container_name: mysql_db
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql