services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: receitas_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql